# Generated by Django 5.0.1 on 2024-02-22 19:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_files_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_path',
            field=models.FilePathField(default=None, path=api.models.Files.user_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=api.models.Files.user_directory_path),
        ),
    ]
