# Generated by Django 5.0.1 on 2024-02-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_files_file_path_alter_files_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file_path',
        ),
    ]
