# Generated by Django 5.0.1 on 2024-02-28 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.folder'),
        ),
    ]
