# Generated by Django 5.0.1 on 2024-02-29 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_folders_alter_files_folder_delete_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Folders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
